### ISSUE TITLE
Flatpak won't open

### ISSUE THREAD

**Issue by eglenelid-gamaliel** [vixalien/muzika#177] opened 2024-07-12 22:12 UTC
![Captura desde 2024-07-12 16-11-15](https://github.com/user-attachments/assets/ee1cacd8-6324-4db0-8acf-65267437d24e)

**Comment by vixalien** [comment] 2024-07-12 22:13
I have the same error on main. I will try to fix this ASAP

**Comment by vixalien** [comment] 2024-07-19 14:35
It seems this error is caused by this patch not being applied (for some reason): https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/master/patches/meson/meson-no-lib64.patch

this causes libportal to be installed at `/app/lib64` instead of `/app/lib` where it won't get picked up. Unfortunately, I don't know what caused this issue.

**Comment by vixalien** [comment] 2024-07-19 14:42
Fixed by b44cc8e

**Comment by vixalien** [comment] 2024-07-19 14:42
just update :)

**Closed by vixalien** 2024-07-19 14:42 UTC

**Comment by eglenelid-gamaliel** [comment] 2024-07-22 17:59
I just updated the app and it's solved, thank you so much!
