### ISSUE TITLE
[mobile] unable to toggle between song and video

### ISSUE THREAD

**Issue by onny** [vixalien/muzika#75] opened 2023-11-01 16:00 UTC
tracks which propably provide both audio track and music video doesn't offer the possibility to switch between these two

<img src="https://github.com/vixalien/muzika/assets/757752/cfd7d539-411f-4781-953d-01de676682d3" width=300px>

**Comment by vixalien** [comment] 2023-11-03 12:58
interesting. does this happen for all songs?

**Comment by onny** [comment] 2023-11-03 13:39
> interesting. does this happen for all songs?

I couldn't find a song where it's possible to toggle between video and audio on mobile

**Comment by vixalien** [comment] 2023-11-03 15:51
Okay. It can happen sometimes when there are many versions of a song on YouTube Music.

Can you search `e6ztG5kjUZo` (letter by letter) it is the video ID of "Just Can't Get Enough" by The Black Eyed Peas. Play the first result. It should have a video counterpart. Please remember to download the latest artefact.

**Comment by vixalien** [comment] 2024-01-15 17:40
Hello! Can you please update me if the issue persists?

**Comment by Alexmitter** [comment] 2024-01-19 19:44
Hello @vixalien, I can confirm this issue. Not just on mobile but on desktop too, currently running the newest build from actions.

**Comment by vixalien** [comment] 2024-01-21 17:13
Hmm that's interesting. If you want to share some more details, do you have YouTube Music Premium? and if so, are you in one of the supported countries: https://support.google.com/youtubemusic/answer/6307365?hl=en

**Comment by Alexmitter** [comment] 2024-02-07 12:15
Hello @vixalien 
I indeed have premium and am in a supported country. Maybe it was some temporary issue because I can not reproduce it anymore for now.

**Comment by vixalien** [comment] 2024-02-07 15:28
Okay. I'm going to close this for now. Please comment again if issues persist

**Closed by vixalien** 2024-02-07 15:28 UTC
Labels: bug, question
