### ISSUE TITLE
Mirror to Codeberg

### ISSUE THREAD

**Issue by sungsphinx** [vixalien/muzika#94] opened 2024-02-03 09:42 UTC
Hi, I think it would be worth setting up mirrors to Codeberg so me, and possibly other people using Codeberg don't need to have a GitHub account or have to use GitHub as much, you can view other reasons at: https://codeberg.org/Recommendations/Mirror_to_Codeberg#why-should-we-mirror-to-codeberg

How to set up:
https://codeberg.org/Recommendations/Mirror_to_Codeberg#github-codeberg-mirroring-tutorial

Using GitHub Actions to mirror and Codeberg mirroring allows contributions from both sides.

### BiblioReads
Codeberg: https://codeberg.org/nesaku/BiblioReads
GitHub: https://github.com/nesaku/BiblioReads

### Doggo
Codeberg: https://codeberg.org/SOrg/Doggo
GitHub: https://github.com/SillyOrgGH/Doggo

**Comment by vixalien** [comment] 2024-02-05 17:49
Hi. While I value my privacy and know the issues with GitHub, I simply don't have the time and energy to do this mirroring setup. It is simply because I'm not interested.

If you really hate GitHub, you can probably set up the mirror yourself, and I would possibly do what I can to support that. Except, I don't necessarily want to fiddle with issues that arise from this mirroring thing. Any insights would be appreciated.

**Comment by vixalien** [comment] 2024-02-05 20:07
Thanks for clarifying, but I'm not that scared of it being a tedious process. What I'm not convinced of is the benefits mirroring to codeberg will have. You are the only contributor who uses that, and honestly you'd be better off running your own mirror and syncing changes automatically as you said it's possible, and an abstraction that creates PRs for you here if you don't want to use GitHub.

I don't really see why this mirroring would be desired at all... You already have a GitHub account. If you don't want to send PRs easily, you can always email me a patch set, and while the process will be slower I will sure take a look at that.

With that said, I'm not convinced at all why I need this, except the "GitHub is bad" argument. I'll go ahead and close this issue but you're free to continue the discussion while the issue is closed.

**Closed** 2024-02-05 20:08 UTC
