### ISSUE TITLE
No way to play video on desktop

### ISSUE THREAD

**Issue by AdrianVovk** [vixalien/muzika#194] opened 2024-08-01 23:28 UTC
With the recent rework of the desktop's "Now playing" UI (in #180), there's no way to play a music video for a song.

My workaround is to shrink the size of the app into a mobile size, then open the now-playing view, then switch it to video, then grow the app again.

**Comment by DaPigGuy** [comment] 2024-08-02 02:40
Duplicate of #187

**Closed** 2024-08-02 02:40 UTC

**Comment by AdrianVovk** [comment] 2024-08-02 12:20
Whoops no idea how I didn't find that one... Sorry for the noise
